[dirs]
# prefix="/usr/local"
# exec_prefix=""
# bindir="bin"
# libdir="lib"
# libexecdir="libexec"
# sbindir="sbin"
# datarootdir="share"
# datadir=""
# mandir="man"
# docdir="doc"
# infodir="info"
# localedir="locale"
# sysconfdir="etc"
# localstatedir="var"
# sharedstatedir="com"
# runstatedir="run"
# usersdir="users"
# groupsdir="groups"
# passwd="passwd"
# shadow="shadow"
# group="group"
# gshadow="gshadow"
# sudoers="sudoers"